name: Test deploy

on:
  pull_request:
    branches:
      - main

permissions: write-all

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20

      - name: Install Node dependencies
        run: npm install --ignore-scripts

      - name: Package using Webpack
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Install Bundler
        run: gem install bundler

      - name: Install Gems
        run: bundle install
      # Deploy to beta.gxcko.me/{{ pr }} branch
      - name: Deploy to beta
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gxcko.me
          cname: beta.gxcko.me
          enable_jekyll: true