name: Test deploy

on:
  pull_request:
    branches:
      - main

permissions: write-all

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.3
        with:
          node-version: 20

      - name: Install Node dependencies
        run: npm install --ignore-scripts

      - name: Build
        run: npm run build

      - name: Copy dist files to source
        run: cp -r gxcko.me/dist/index.html gxcko.me/index.html && cp -r gxcko.me/dist/assets gxcko.me/assets

      - name: Clean up ./dist
      - run: rmdir gxcko.me/dist/assests && rm gxcko.me/dist/index.html

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./gxcko.me
          destination: ./_site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
