name: unit-tests
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.3
        with:
          node-version: 20

      - name: Install Node dependencies
        run: npm install --ignore-scripts

      - name: Run tests
        run: npm run test:cov